version: '2'

services:
    haproxy:
      build: .
      hostname: haproxy
      ports:
        - "5672:5672"  # mq
        - "1936:1936"  # haproxy status
        - "15672:15672" # mq_ui
      volumes:
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        - ./docker-entrypoint-override.sh:/docker-entrypoint-override.sh
        - ./keepalived:/keepalived
      networks: 
        - front-tier
        - back-tier

networks:
    front-tier:
      driver: bridge
    back-tier:
      driver: bridge
