output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["http://elasticsearch:9200"] ## Monitoring cluster

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "kibana:5601"
  username: "elasitc"
  password: "changeme"

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  #path: /usr/share/metricbeat/modules.d/*.yml


http.enabled: true
http.port: 5066
monitoring.enabled: false

metricbeat.modules:
- module: beat
  metricsets:
    - stats
    - state
  period: 10s
  hosts: ["http://localhost:5066"]
  #username: "user"
  #password: "secret"
  xpack.enabled: true

# elasticsearch-xpack: 不能解决metricbeat启动的问题,还是用modules.d/来做
#- module: elasticsearch
  #xpack.enabled: true
  #period: 10s
  #hosts: ["http://elasticsearch:9200"]
  #username: "elastic"
  #password: "changeme"

# 和logstash一样,metricbeat也要以metricbeat-*来做默认索引
# Connection marked as failed because the onConnect callback failed: resource 'metricbeat-7.8.0' exists, but it is not an alias
#
#output.elasticsearch.index: "logstash-nginx-test-%{+yyyy.MM} "
#setup.template.name: "logstash"
#setup.template.pattern: "logstash-*"
