output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["http://elasticsearch:9200"] ## Monitoring cluster

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "kibana:5601"
  username: "elasitc"
  password: "changeme"

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  #path: /usr/share/metricbeat/modules.d/*.yml
