output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["http://elasticsearch:9200"] ## Monitoring cluster

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "kibana:5601"
  username: "elasitc"
  password: "changeme"

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  #path: /usr/share/metricbeat/modules.d/*.yml


http.enabled: true
http.port: 5066
monitoring.enabled: false

metricbeat.modules:
- module: beat
  metricsets:
    - stats
    - state
  period: 10s
  hosts: ["http://localhost:5066"]
  #username: "user"
  #password: "secret"
  xpack.enabled: true

# elasticsearch-xpack
- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
