version: '2'

services:
    mysql:
        #image: mysql
        image: mysql:5.7
        #build: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=mxshop1
            - MYSQL_USER=root
            - MYSQL_PASSWORD=123456
            - MYSQL_HOST=0.0.0.0
            - MYSQL_PORT=3306  # cannot change this port to other number
            - MYSQL_ROOT_HOST=%

        ports:
            - '3306:3306'
        volumes:
            - './database/mysql:/var/lib/mysql'
        #   - xx:/var/lib/mysql  
        #   会自动在/var/lib/docker/volumes下,创建dockerfiles_xx目录

    redis:
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '6379:6379'
            # (HOST:CONTAINER)
        volumes:
            - ./database/redis:/bitnami
        restart: always

    web:
        #restart: always
        build: ../MxShop

        #expose:
        ports:
            - "8000:8000"
            # (HOST:CONTAINER(nginx)
        links:
            - mysql
            - redis
        volumes:
            - '../MxShop:/code'
            # (HOST:CONTAINER)
            #- /usr/src/app/static
        environment:
            - DEBUG= 'true'
        #command: python3 manage.py runserver 0.0.0.0:8000
        command: uwsgi --ini uwsgi.ini
        
        #command: bash -c "python3 manage.py makemigrations &&
                #python3 manage.py migrate &&
                #python3 init_admin.py &&
                #python3 manage.py runserver 0.0.0.0:8000"
                #
                #/usr/local/bin/gunicorn --bind 0.0.0.0:8000 MxShop.wsgi:application -w 2"


    nginx:
        restart: always
        build: nginx
        container_name: nginx-container
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./nginx/log:/var/log/nginx
            - ./nginx/www:/usr/share/nginx/html
        volumes_from:
            - web
        links:
            - web:drf_web

        #docker run --name mysql1 -p 80:80 -v /home/femn/Documents/docker-django/Dockerfiles/nginx/www:/usr/share/nginx/html:ro  -d nginx
        
    #nginx-proxy:
        #image: jwilder/nginx-proxy
        #ports:
            #- "80:80"
        #volumes:
            #- /var/run/docker.sock:/tmp/docker.sock:ro
            #- ./nginx/conf.d:/etc/nginx/conf.d
            #- ./nginx/log:/var/log/nginx
            #- ./nginx/www:/usr/share/nginx/html
        #volumes_from:
            #- web
        #links:
            #- web:drf_web
            #docker run --name mysql1  -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro -d jwilder/nginx-proxy
            #docker run --name mysql1  -p 80:80 -v /home/femn/Documents/docker-django/Dockerfiles/nginx/www:/usr/share/nginx/html:ro -d jwilder/nginx-proxy



