# Module: logstash
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.8/metricbeat-module-logstash.html

- module: logstash
  xpack.enabled: true
  period: 10s
  hosts: ["logstash:9600"]
  username: "elasitc"
  password: "changeme"
  #username: "user"
  #password: "secret"
