filebeat.inputs:
#- type: log
  #enabled: true
  #paths:
    #- /usr/share/filebeat/mylogs/*/*.log

- type: log
  enabled: true 
  paths:
    - /usr/share/filebeat/mylogs/nginx/access.log
    - /usr/share/filebeat/mylogs/nginx/new_json_access.log 
  json.keys_under_root: true
  json.overwrite_keys: true
  tags: ["access"]

- type: log
  enabled: true 
  paths:
    - /usr/share/filebeat/mylogs/nginx/error.log
  tags: ["error"]



setup.kibana:
  host: "kibana:5601"

# filebeat只能有一个类型的output,
output.logstash:
  hosts: ["logstash:5044"]
  #enabled: true 

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"



