version: '2'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:alpine-trunk
  container_name: zabbix-server
  ports:
   - "10051:10051"
  volumes:
   # echo "Asia/Shanghai" > /private/etc/timezone
   #- /private/etc/localtime:/etc/localtime
   #- /private/etc/timezone:/etc/timezone
   - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
   #- ./zbx_env/usr/share/doc:/usr/share/doc
   #- ./zbx_env/usr/share/doc/zabbix-server-mysql:/usr/share/doc/zabbix-server-mysql
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs
  volumes_from:
   - zabbix-snmptraps
  links:
   - mysql-server:mysql-server
   # 被动代理
   - zabbix-java-gateway:zabbix-java-gateway
   # 被动代理
   #- zabbix-proxy-mysql:zabbix-proxy-mysql
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  mem_limit: 512m
  env_file:
   - .env_db_mysql
   - .env_srv
  networks:
   - zbx_net_frontend
   - zbx_net_backend

 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:alpine-trunk
  #image: zabbix/zabbix-web-nginx-mysql:alpine-3.4-latest
  ports:
   - "8081:8080"  # 我说死活从外网打不开呢,原来容器的端口是8080,而不是80
   - "8443:8443"
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  mem_limit: 512m
  volumes:
   #- /private/etc/localtime:/etc/localtime
   #- /private/etc/timezone:/etc/timezone
   - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx
   - ./simkai.ttf:/usr/share/zabbix/fonts/graphfont.ttf
  env_file:
   - .env_db_mysql
   - .env_web
  networks:
   - zbx_net_frontend
   - zbx_net_backend

 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-trunk
  container_name: zabbix-agent
  ports:
   - "10050:10050"
  volumes:
   #- /private/etc/localtime:/etc/localtime
   #- /private/etc/timezone:/etc/timezone
   - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys
  links:
   - zabbix-server:zabbix-server
  env_file:
   - .env_agent

  #network_mode: host

  privileged: true
  pid: "host"

  networks:
   #- zbx_net_frontend
   - zbx_net_backend

 zabbix-java-gateway:
   image: zabbix/zabbix-java-gateway:alpine-trunk
   ports:
    - "10052:10052"
   env_file:
    - .env_java
   networks:
    - zbx_net_frontend
    - zbx_net_backend

 #zabbix-proxy-mysql:
   #image: zabbix/zabbix-proxy-mysql:alpine-trunk
   #ports:
    #- "10051:10051"
  #volumes:
   #- ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
   #- ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
   #- ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules
   #- ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc
   #- ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys
   #- ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs
  #links:
   #- zabbix-server:zabbix-server
   #env_file:
    #- .env_proxy_mysql
 
 zabbix-snmptraps:
   image: zabbix/zabbix-snmptraps:alpine-trunk
   ports:
    - "162:162/udp"
   volumes:
    - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps
   networks:
    - zbx_net_frontend
    - zbx_net_backend

 mysql-server:
  image: mysql:5.7
  #volume_driver: local
  #command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]
  #volumes_from:
    #- db_data_mysql
  command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
  # , --default-authentication-plugin=mysql_native_password  8.0
  volumes:
    - './database/mysql:/var/lib/mysql'
    - './femn.conf:/etc/mysql/mysql.conf.d/femn.cnf'
  ports:
    - '3309:3306'
  env_file:
   - .env_db_mysql
  networks:
   - zbx_net_frontend
   - zbx_net_backend

 db_data_mysql:
    image: busybox
    volumes:
    - ./zbx_env/var/lib/mysql:/var/lib/mysql
    networks:
      - zbx_net_frontend
      - zbx_net_backend


networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
